import type { Metadata } from 'next'
import './globals.css'
import { ReactNode } from 'react'
import Link from 'next/link'
import { AuthProvider } from '@/contexts/AuthContext'
import HeaderNav from '@/components/HeaderNav'
import DDWLogo from '@/components/DDWLogo'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutProps {
  children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang="ko">
      <body className="font-sans antialiased">
        <AuthProvider>
          <div className="relative min-h-screen bg-slate-50">
            {/* 은은한 배경 그라데이션과 그리드 패턴 추가 */}
            <div className="absolute inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-[size:6rem_4rem]">
              <div className="absolute bottom-0 left-0 right-0 top-0 bg-[radial-gradient(circle_500px_at_50%_200px,#c9d5ff,transparent)] opacity-30"></div>
            </div>
            {/* Header */}
            <header className="fixed w-full top-0 z-50 backdrop-blur-md bg-white/80 border-b border-gray-200/80">
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex justify-between items-center h-16">
                  <Link
                    href="/"
                    className="flex items-center"
                    aria-label="DDW 홈으로"
                  >
                    <DDWLogo className="h-8 w-auto" />
                  </Link>
                  <HeaderNav />
                </div>
              </div>
            </header>

            {/* Main Content */}
            <main className="pt-16 flex-grow">{children}</main>

            {/* Footer */}
            <footer className="bg-white border-t border-gray-200">
              <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
                <p className="text-center text-sm text-gray-500">
                  &copy; 2025 DDW. All rights reserved.
                </p>
              </div>
            </footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
